### ISSUE TITLE
BadMethodCallException with message 'This cache store does not support tagging.'

### ISSUE THREAD

**Issue by Synchro** [stechstudio/laravel-hubspot#1]
I'm running into a problem with a simple use of your package. I'm getting a bunch of deals like this:

```php
$deals = Deal::where('dealstage', '=', 'closedwon')
->orderBy('amount', 'desc')
->take(10)
->get();
foreach ($deals as $deal) {
  dump($deal->dealname);
}
```
But this throws the `BadMethodCallException with message 'This cache store does not support tagging.'` error as soon as I try to access a property on a response, in this example `$deal->dealname`. I can see that this library is using [cache tagging](https://github.com/stechstudio/laravel-hubspot/blob/main/src/Api/PropertyDefinition.php#L53), but as I'm using the `file` cache in development, it fails, [as per the Laravel docs](https://laravel.com/docs/9.x/cache#cache-tags).

Switching to the `array` cache driver works, however, is there some way to make this fail a bit more clearly, or to be made to work with caches that do not support tags, for example by prefixing keys or something?

**Comment by Synchro** [comment]
I should mention that your package is an **enormous** improvement over the complete disaster I had trying to use the official HubSpot package!

**Comment by jszobody** [comment]
Thanks for the encouragement!

I hadn't even considered that someone might be try to use cache that doesn't support tags. I use redis locally, it's trivial to set up on a Mac at least. 

I'm not even sure I really need the tags. I added those thinking it would make flushing/invalidating cache easier, at some point. But it's not something I'm doing right now. 

If this line was changed to no longer implement tags:

https://github.com/stechstudio/laravel-hubspot/blob/0989974c5081c5aeaf8426719694eb08559b455a/src/Api/PropertyDefinition.php#L55

I think it would be fine. I can look at making that change soon, or you could toss me a PR if you want.

**Comment by Synchro** [comment]
[Laravel defaults to using a `file` cache](https://github.com/laravel/laravel/blob/9.x/config/cache.php#L18), so I think it's worth making it work "out of the box".

It might be nice to use tags if they are available, but otherwise don't try. Unfortunately I've not seen if there's an easy way to tell – I've not used Laravel's cache much.

**Comment by Synchro** [comment]
Thanks
