### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by derekcavaliero** [stechstudio/laravel-hubspot#14]
First of all - this looks to be a huge improvement from a DX perspective compared to the attrocity that the main HubSpot PHP API client is. So thank you for making/maintaining this.

Apologies if I am simply being dumb/missing something but I cannot get this to work based on the syntax/examples in the readme.

I did the following:

- Installed the package via Composer
- Added `STS\HubSpot\HubSpotServiceProvider::class` to the `providers` array in `config/app.php`
- Added `'HubSpot' => STS\HubSpot\Facades\HubSpot::class` to the `aliases` array in `config/app.php` 
- Added `use HubSpot` to the file where I want to leverage the API (also tried `use STS\HubSpot\Facades\HubSpot` in case my alias was wrong)

No matter what I do - the examples where it uses `Contacts::where()` won't work. The level of abstraction here is confusing me - and I guarantee this is me being something silly. It's saying that the methods aren't defined.

**Comment by jszobody** [comment]
You shouldn't have to add the `HubSpotServicerProvider`, that's wired up for you [in the composer.json file automatically](https://github.com/stechstudio/laravel-hubspot/blob/main/composer.json#L63-L69).

Are you importing the model class first?

```
use STS\HubSpot\Crm\Contact;

dd(Contact::where('state','NC')); // <-- should give you an instance of `STS\HubSpot\Api\\Builder`
```

Here is a screenshot from Tinkerwell where I just tried the above:

<img width="514" alt="CleanShot 2023-07-21 at 09 31 43@2x" src="https://github.com/stechstudio/laravel-hubspot/assets/203749/b6615c97-138e-46a9-8b9c-1da092f74975">

**Comment by derekcavaliero** [comment]
Ahhh - I see. Thank you @jszobody it was indeed me being a dummy. Thanks a bunch appreciate it.
