### ISSUE TITLE
Mapping oddity

### ISSUE THREAD

**Issue by Synchro** [stechstudio/laravel-hubspot#2]
I've got something funny going on and can't see what it might be. I'm getting some deals like this:

```php
$deals = Deal::where('dealstage', '=', 'closedwon')
    ->orderBy('amount', 'desc')
    ->take(10)
    ->get();  
```

and I want to pick out just the `dealname` and `amount` properties into a new collection. This code works fine:

```php
  $dealData = new Collection();
  foreach ($deals as $deal) {
    $dealData->add(
      (object) [
        'name' => $deal->dealname,
        'amount' => $deal->amount,
      ]
    );
  }
```

but this does not, producing a collection of nulls instead:

```php
$dealData = $deals->map(function ($deal) {
    return $deal->only(['dealname', 'amount']);
});

//or the same thing using higher-order messages:

$dealData = $deals->map->only(['dealname', 'amount']);
```
The properties are clearly there, as otherwise the `for` loop code wouldn't work. The only thing I can think of is that the `Deal` objects are somehow incompatible with `only()`. Any idea why that might be?

**Comment by jszobody** [comment]
Update to 0.1.1 and it should work. There was no `only()` method in the Model class.

**Comment by Synchro** [comment]
Thank you very much, that works fine. It was my mistake in assuming that the `Model` you were using was a subclass/implementation of the Illuminate Model, rather than your own thing.
