### ISSUE TITLE
[Feature] Support for v4 associations API

### ISSUE THREAD

**Issue by BinaryKitten** [stechstudio/laravel-hubspot#6]
Hubspot have changed their associations API and introduced a v4. This works quite differently to before with extra data needed for creation of the relationship etc.

Can we look to get this supported?

**Comment by jszobody** [comment]
Not looking to implement v4 associations anytime soon. I don't see any benefit for the SDK consumer. As long as Hubspot keeps v3 available and supported, I'm not sure it's worth the effort just yet. That might change down the road.
