### ISSUE TITLE
[Feature] Add Owners support

### ISSUE THREAD

**Issue by BinaryKitten** [stechstudio/laravel-hubspot#8]
Owners of Deals and contacts are important data point within the Hubspot CRM ecosystem - we should add support for them.

**Comment by rjm87** [comment]
Is there any update on this?

**Comment by BinaryKitten** [comment]
Non as yet.
I no longer have any test account presently to help integrate with as changed employers.

This feature was added as a note for future but open to anyone to create a pr for the functionality.
